import React, { createContext, useState, useContext, useEffect } from 'react';
import i18n from '../i18n'; // Import i18n to sync language changes

const LanguageContext = createContext(null);

const translations = {
  hu: {
    // Navigation
    nav_overview: 'Áttekintés',
    nav_scripts: 'Script Generátor',
    nav_hooks: 'Hook Könyvtár',
    nav_videos: 'Videó Gyár',
    nav_analytics: 'Analitika',
    nav_notion: 'Notion Analitika',
    nav_settings: 'Beállítások',
    nav_logout: 'Kijelentkezés',
    
    // Auth
    login_title: 'Bejelentkezés',
    register_title: 'Regisztráció',
    email: 'E-mail',
    password: 'Jelszó',
    name: 'Név',
    login_button: 'Bejelentkezés',
    register_button: 'Regisztráció',
    forgot_password: 'Elfelejtett jelszó',
    reset_password: 'Jelszó visszaállítás',
    
    // Dashboard Overview
    welcome: 'Üdvözöl',
    welcome_message: 'Készen állsz piacképes YouTube Shorts-okat készíteni?',
    total_scripts: 'Scriptek',
    total_hooks: 'Hookok',
    avg_retention: 'Retention %',
    swipe_rate: 'Swipe Rate %',
    recent_scripts: 'Legutóbbi Scriptek',
    no_scripts_yet: 'Még nincs script',
    create_first_script: 'Hozd létre az első scriptedet a generátorban',
    quick_actions: 'Gyors Műveletek',
    script_generation: 'Script Generálás',
    script_generation_desc: 'AI-powered német faith scriptek',
    video_creation: 'Videó Készítés',
    video_creation_desc: 'TTS + B-roll + karaoke',
    analytics_upload: 'Analytics Feltöltés',
    analytics_upload_desc: 'CSV import Notion-ből',
    how_to_start: 'Hogyan kezdj neki?',
    how_to_start_desc: 'Kövesd ezeket a lépéseket a sikeres YouTube Shorts készítéséhez',
    step_1_title: 'Generálj AI scripteket',
    step_1_desc: 'Emotional faith-based tartalommal',
    step_2_title: 'Töltsd fel analytics adatokat',
    step_2_desc: 'CSV-ből vagy Notion API-val',
    step_3_title: 'ML-optimalizált generálás',
    step_3_desc: 'Top patterns alapján',
    step_4_title: 'Készíts piacképes videót',
    step_4_desc: 'Teljes video pipeline',
    
    // Script Generator
    script_generator: 'Script Generátor',
    script_generator_subtitle: 'AI-powered német faith-niche YouTube Shorts scriptek',
    settings: 'Beállítások',
    ml_optimized_generation: 'ML-Optimalizált Generálás',
    use_top_patterns: 'Használd a top performing patterns-t az analytics adatokból',
    topic: 'Téma',
    topic_placeholder: 'pl. Isten szeretete, Ima ereje, stb.',
    topic_required: 'Kérlek adj meg egy témát!',
    keywords: 'Kulcsszavak',
    keyword_placeholder: 'pl. Hoffnung',
    add_keyword: 'Kulcsszó hozzáadása',
    mode: 'Mód',
    use_analytics: 'Analitika használata (ML optimalizáció)',
    analytics_disabled: 'Nincs elég analytics adat az ML-optimalizációhoz',
    generate: 'Generálás',
    ml_generate: 'ML-Optimalizált Generálás',
    generating: 'Generálás...',
    generated_script: 'Generált Script',
    generated_with_analytics: 'ML-optimalizálva analytics alapján',
    script_success: 'Script sikeresen generálva!',
    script_failed: 'Script generálás sikertelen',
    no_script_yet: 'Még nincs generált script.',
    enter_topic_generate: 'Add meg a témát és kattints a Generálás gombra!',
    hook: 'Hook',
    full_script: 'Teljes script',
    character_count: 'karakter',
    copied: 'Másolva!',
    top_patterns: 'Top Patterns',
    swipe_rate: 'Swipe Rate',
    full_script: 'Teljes Script',
    character_count: 'Karakterszám',
    hook_type: 'Hook Típus',
    generated_with_analytics: 'ML-optimalizált',
    copy: 'Másolás',
    copied: 'Vágólapra másolva!',
    
    // Hook Library
    hook_library: 'Hook Könyvtár',
    hook_library_subtitle: 'Automatikus és manuális gyűjtemény',
    hook_count: 'hook',
    search_hooks: 'Hook szöveg vagy tag keresése...',
    all_modes: 'Összes Mód',
    all_types: 'Összes Típus',
    sort_by: 'Rendezés',
    sort_date: 'Dátum',
    sort_retention: 'Retention %',
    sort_usage: 'Használat',
    create_hook: 'Új Hook',
    create_hook_title: 'Új Hook Létrehozása',
    hook_text: 'Hook Szöveg',
    hook_text_placeholder: 'Weißt du, was wirklich zählt?',
    hook_type: 'Hook Típus',
    avg_retention: 'Átlag Retention %',
    retention: 'retention',
    usage_count: 'használva',
    times_used: '× használva',
    tags: 'Tagek',
    tag_placeholder: 'pl. Hoffnung',
    delete: 'Törlés',
    add_tag: 'Hozzáadás',
    no_hooks_yet: 'Még nincs hook',
    no_results: 'Nincs találat',
    try_different_filters: 'Próbálj meg más keresési feltételeket',
    create_first_hook: 'Generálj scripteket vagy hozz létre manuálisan hookokat',
    hook_created: 'Hook létrehozva!',
    hook_deleted: 'Hook törölve',
    hook_text_required: 'Hook szöveg megadása kötelező!',
    hook_load_failed: 'Hook library betöltése sikertelen',
    hook_create_failed: 'Hook létrehozása sikertelen',
    hook_delete_failed: 'Törlés sikertelen',
    confirm_delete_hook: 'Biztosan törlöd ezt a hookot?',
    loading: 'Betöltés...',
    
    // Hook Types
    emotional_trigger: 'Emotional Trigger',
    urgency: 'Urgency',
    identity_filter: 'Identity Filter',
    reverse_psychology: 'Reverse Psychology',
    not_for_everyone: 'Not For Everyone',
    dominance_line: 'Dominance Line',
    open_loop: 'Open Loop',
    
    // Video Factory
    video_factory: 'Videó Gyár',
    video_factory_subtitle: 'AI-powered videó generálás: TTS + B-roll + karaoke feliratok',
    select_script: 'Script Kiválasztása',
    select_script_prompt: 'Válassz egy scriptet...',
    voice_settings: 'Hang Beállítások (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'pl. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stability',
    similarity_boost: 'Similarity Boost',
    style: 'Style',
    speaker_boost: 'Speaker Boost (ajánlott)',
    video_settings: 'Videó Beállítások',
    broll_search: 'B-roll Keresés (Pexels)',
    broll_placeholder: 'pl. faith, spirituality, peaceful (üres = auto topic)',
    broll_hint: 'Ha üresen hagyod, a script topic-ját használja',
    background_music: 'Háttérzene URL (opcionális)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock music vagy saját URL (MP3)',
    start_generation: 'Videó Generálás Indítása',
    generation_in_progress: 'Generálás folyamatban...',
    video_pipeline: 'Videó Pipeline',
    generated_videos: 'Generált Videók',
    no_videos_yet: 'Még nincs generált videó',
    select_and_generate: 'Válassz egy scriptet és indítsd el a videó generálást!',
    
    // Analytics
    analytics: 'Analytics Dashboard',
    analytics_subtitle: 'Performance metrikák és insights',
    total_views: 'Összes Megtekintés',
    total_likes: 'Összes Like',
    total_comments: 'Kommentek',
    new_subscribers: 'Új Feliratkozók',
    avg_retention_rate: 'Átlag Retention Rate',
    avg_swipe_rate: 'Átlag Swipe Rate',
    excellent: 'Kiváló',
    improvable: 'Fejleszthető',
    hook_type_performance: 'Hook Típus Performance',
    latest_metrics: 'Legutóbbi Metrikák',
    no_analytics_yet: 'Még nincs analytics adat',
    upload_csv_or_add_metrics: 'Töltsd fel a Notion CSV-t vagy adj hozzá metrics-et',
    
    // Notion Analytics
    notion_analytics: 'Notion Analitika',
    notion_subtitle: 'CSV import/export és ML optimization insights',
    import_csv: 'CSV Importálás',
    export_csv: 'Adatok Exportálása',
    view_guide: 'Algoritmus Guide',
    analytics_insights: 'Analytics Insights',
    imported_rows: 'Importált Sorok',
    top_hooks: 'Top Performans Hookok',
    top_scripts: 'Top Performans Scriptek',
    no_data_yet: 'Még nincs Notion adat',
    import_csv_to_start: 'Importálj CSV-t az ML optimization használatához',
    
    // Settings
    settings_title: 'Beállítások',
    settings_subtitle: 'Profil és API kulcsok kezelése',
    profile: 'Profil',
    api_keys: 'API Kulcsok',
    api_keys_warning: '⚠️ Figyelem: A kulcsok a böngésző localStorage-ban tárolódnak!',
    save_keys: 'Kulcsok Mentése',
    keys_saved: 'API kulcsok mentve!',
    logout: 'Kijelentkezés',
    logout_subtitle: 'Munkamenet befejezése',
    logout_success: 'Sikeresen kijelentkeztél!',
    
    // Common
    save: 'Mentés',
    cancel: 'Mégse',
    close: 'Bezárás',
    edit: 'Szerkesztés',
    loading: 'Betöltés...',
    error: 'Hiba',
    success: 'Siker',
    characters: 'karakter',
    created_at: 'Létrehozva',
    updated_at: 'Frissítve'
  },
  
  de: {
    // Navigation
    nav_overview: 'Übersicht',
    nav_scripts: 'Skript-Generator',
    nav_hooks: 'Hook-Bibliothek',
    nav_videos: 'Video-Fabrik',
    nav_analytics: 'Analytik',
    nav_notion: 'Notion Analytik',
    nav_settings: 'Einstellungen',
    nav_logout: 'Abmelden',
    
    // Auth
    login_title: 'Anmelden',
    register_title: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    name: 'Name',
    login_button: 'Anmelden',
    register_button: 'Registrieren',
    forgot_password: 'Passwort vergessen',
    reset_password: 'Passwort zurücksetzen',
    
    // Dashboard Overview
    welcome: 'Willkommen',
    welcome_message: 'Bereit, marktfähige YouTube Shorts zu erstellen?',
    total_scripts: 'Skripte',
    total_hooks: 'Hooks',
    avg_retention: 'Retention %',
    swipe_rate: 'Swipe Rate %',
    recent_scripts: 'Neueste Skripte',
    no_scripts_yet: 'Noch keine Skripte',
    create_first_script: 'Erstelle dein erstes Skript im Generator',
    quick_actions: 'Schnellaktionen',
    script_generation: 'Skript-Erstellung',
    script_generation_desc: 'KI-gestützte deutsche Glaubens-Skripte',
    video_creation: 'Video-Erstellung',
    video_creation_desc: 'TTS + B-Roll + Karaoke',
    analytics_upload: 'Analytics-Upload',
    analytics_upload_desc: 'CSV-Import aus Notion',
    how_to_start: 'Wie fange ich an?',
    how_to_start_desc: 'Folge diesen Schritten für erfolgreiche YouTube Shorts',
    step_1_title: 'KI-Skripte generieren',
    step_1_desc: 'Emotionale Glaubens-Inhalte',
    step_2_title: 'Analytics-Daten hochladen',
    step_2_desc: 'Aus CSV oder Notion API',
    step_3_title: 'ML-optimierte Generierung',
    step_3_desc: 'Basierend auf Top-Patterns',
    step_4_title: 'Marktfähiges Video erstellen',
    step_4_desc: 'Vollständige Video-Pipeline',
    
    // Script Generator
    script_generator: 'Skript-Generator',
    script_generator_subtitle: 'KI-gestützte deutsche Glaubens-Nische YouTube Shorts Skripte',
    settings: 'Einstellungen',
    ml_optimized_generation: 'ML-Optimierte Generierung',
    use_top_patterns: 'Verwenden Sie Top-Muster aus Analytics-Daten',
    top_patterns: 'Top-Muster',
    topic: 'Thema',
    topic_placeholder: 'z.B. Gottes Liebe, Kraft des Gebets, usw.',
    topic_required: 'Bitte geben Sie ein Thema ein!',
    keywords: 'Schlüsselwörter',
    keyword_placeholder: 'z.B. Hoffnung',
    add_keyword: 'Schlüsselwort hinzufügen',
    mode: 'Modus',
    use_analytics: 'Analytik verwenden (ML-Optimierung)',
    analytics_disabled: 'Nicht genug Analytik-Daten',
    generate: 'Generieren',
    ml_generate: 'ML-Optimierte Generierung',
    generating: 'Wird generiert...',
    generated_script: 'Generiertes Skript',
    generated_with_analytics: 'ML-optimiert basierend auf Analytics',
    script_success: 'Skript erfolgreich generiert!',
    script_failed: 'Skript-Generierung fehlgeschlagen',
    no_script_yet: 'Noch kein Skript generiert.',
    enter_topic_generate: 'Geben Sie ein Thema ein und klicken Sie auf Generieren!',
    hook: 'Hook',
    full_script: 'Vollständiges Skript',
    character_count: 'Zeichen',
    copied: 'Kopiert!',
    swipe_rate: 'Swipe-Rate',
    full_script: 'Vollständiges Skript',
    character_count: 'Zeichenzahl',
    hook_type: 'Hook-Typ',
    generated_with_analytics: 'ML-optimiert',
    copy: 'Kopieren',
    copied: 'In Zwischenablage kopiert!',
    
    // Hook Library
    hook_library: 'Hook-Bibliothek',
    hook_library_subtitle: 'Automatische und manuelle Sammlung',
    hook_count: 'hook',
    search_hooks: 'Hook-Text oder Tag suchen...',
    all_modes: 'Alle Modi',
    all_types: 'Alle Typen',
    sort_by: 'Sortieren',
    sort_date: 'Datum',
    sort_retention: 'Retention %',
    sort_usage: 'Verwendung',
    create_hook: 'Neuer Hook',
    create_hook_title: 'Neuen Hook erstellen',
    hook_text: 'Hook-Text',
    hook_text_placeholder: 'Weißt du, was wirklich zählt?',
    hook_type: 'Hook-Typ',
    avg_retention: 'Durchschn. Retention %',
    retention: 'retention',
    usage_count: 'verwendet',
    times_used: '× verwendet',
    tags: 'Tags',
    tag_placeholder: 'z.B. Hoffnung',
    delete: 'Löschen',
    add_tag: 'Hinzufügen',
    no_hooks_yet: 'Noch keine Hooks',
    no_results: 'Keine Ergebnisse',
    try_different_filters: 'Versuche andere Suchkriterien',
    create_first_hook: 'Generiere Skripte oder erstelle manuell Hooks',
    hook_created: 'Hook erstellt!',
    hook_deleted: 'Hook gelöscht',
    hook_text_required: 'Hook-Text ist erforderlich!',
    hook_load_failed: 'Laden der Hook-Bibliothek fehlgeschlagen',
    hook_create_failed: 'Hook-Erstellung fehlgeschlagen',
    hook_delete_failed: 'Löschen fehlgeschlagen',
    confirm_delete_hook: 'Möchten Sie diesen Hook wirklich löschen?',
    loading: 'Wird geladen...',
    
    // Hook Types
    emotional_trigger: 'Emotionaler Trigger',
    urgency: 'Dringlichkeit',
    identity_filter: 'Identitätsfilter',
    reverse_psychology: 'Umgekehrte Psychologie',
    not_for_everyone: 'Nicht für jeden',
    dominance_line: 'Dominanzlinie',
    open_loop: 'Offene Schleife',
    
    // Video Factory
    video_factory: 'Video-Fabrik',
    video_factory_subtitle: 'KI-gestützte Videogenerierung: TTS + B-Roll + Karaoke-Untertitel',
    select_script: 'Skript auswählen',
    select_script_prompt: 'Wähle ein Skript...',
    voice_settings: 'Stimmeneinstellungen (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'z.B. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stabilität',
    similarity_boost: 'Ähnlichkeits-Boost',
    style: 'Stil',
    speaker_boost: 'Lautsprecher-Boost (empfohlen)',
    video_settings: 'Video-Einstellungen',
    broll_search: 'B-Roll-Suche (Pexels)',
    broll_placeholder: 'z.B. Glaube, Spiritualität, friedlich (leer = Auto-Thema)',
    broll_hint: 'Wenn leer, wird das Skript-Thema verwendet',
    background_music: 'Hintergrundmusik URL (optional)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock-Musik oder eigene URL (MP3)',
    start_generation: 'Videogenerierung starten',
    generation_in_progress: 'Generierung läuft...',
    video_pipeline: 'Video-Pipeline',
    generated_videos: 'Generierte Videos',
    no_videos_yet: 'Noch keine generierten Videos',
    select_and_generate: 'Wähle ein Skript und starte die Videogenerierung!',
    
    // Analytics
    analytics: 'Analytics-Dashboard',
    analytics_subtitle: 'Leistungsmetriken und Einblicke',
    total_views: 'Gesamtansichten',
    total_likes: 'Gesamte Likes',
    total_comments: 'Kommentare',
    new_subscribers: 'Neue Abonnenten',
    avg_retention_rate: 'Durchschn. Retention-Rate',
    avg_swipe_rate: 'Durchschn. Swipe-Rate',
    excellent: 'Ausgezeichnet',
    improvable: 'Verbesserbar',
    hook_type_performance: 'Hook-Typ-Leistung',
    latest_metrics: 'Neueste Metriken',
    no_analytics_yet: 'Noch keine Analytik-Daten',
    upload_csv_or_add_metrics: 'Lade die Notion CSV hoch oder füge Metriken hinzu',
    
    // Notion Analytics
    notion_analytics: 'Notion Analytik',
    notion_subtitle: 'CSV-Import/Export und ML-Optimierungs-Einblicke',
    import_csv: 'CSV importieren',
    export_csv: 'Daten exportieren',
    view_guide: 'Algorithmus-Leitfaden',
    analytics_insights: 'Analytik-Einblicke',
    imported_rows: 'Importierte Zeilen',
    top_hooks: 'Top-Leistungs-Hooks',
    top_scripts: 'Top-Leistungs-Skripte',
    no_data_yet: 'Noch keine Notion-Daten',
    import_csv_to_start: 'Importiere CSV für ML-Optimierung',
    
    // Settings
    settings_title: 'Einstellungen',
    settings_subtitle: 'Profil- und API-Schlüsselverwaltung',
    profile: 'Profil',
    api_keys: 'API-Schlüssel',
    api_keys_warning: '⚠️ Achtung: Schlüssel werden im Browser-localStorage gespeichert!',
    save_keys: 'Schlüssel speichern',
    keys_saved: 'API-Schlüssel gespeichert!',
    logout: 'Abmelden',
    logout_subtitle: 'Sitzung beenden',
    logout_success: 'Erfolgreich abgemeldet!',
    
    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    edit: 'Bearbeiten',
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    characters: 'Zeichen',
    created_at: 'Erstellt',
    updated_at: 'Aktualisiert'
  },
  
  en: {
    // Navigation
    nav_overview: 'Overview',
    nav_scripts: 'Script Generator',
    nav_hooks: 'Hook Library',
    nav_videos: 'Video Factory',
    nav_analytics: 'Analytics',
    nav_notion: 'Notion Analytics',
    nav_settings: 'Settings',
    nav_logout: 'Logout',
    
    // Auth
    login_title: 'Login',
    register_title: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    login_button: 'Login',
    register_button: 'Register',
    forgot_password: 'Forgot Password',
    reset_password: 'Reset Password',
    
    // Dashboard Overview
    welcome: 'Welcome',
    welcome_message: 'Ready to create market-ready YouTube Shorts?',
    total_scripts: 'Scripts',
    total_hooks: 'Hooks',
    avg_retention: 'Retention %',
    swipe_rate: 'Swipe Rate %',
    recent_scripts: 'Recent Scripts',
    no_scripts_yet: 'No scripts yet',
    create_first_script: 'Create your first script in the generator',
    quick_actions: 'Quick Actions',
    script_generation: 'Script Generation',
    script_generation_desc: 'AI-powered German faith scripts',
    video_creation: 'Video Creation',
    video_creation_desc: 'TTS + B-roll + karaoke',
    analytics_upload: 'Analytics Upload',
    analytics_upload_desc: 'CSV import from Notion',
    how_to_start: 'How to Start?',
    how_to_start_desc: 'Follow these steps for successful YouTube Shorts',
    step_1_title: 'Generate AI scripts',
    step_1_desc: 'Emotional faith-based content',
    step_2_title: 'Upload analytics data',
    step_2_desc: 'From CSV or Notion API',
    step_3_title: 'ML-optimized generation',
    step_3_desc: 'Based on top patterns',
    step_4_title: 'Create market-ready video',
    step_4_desc: 'Complete video pipeline',
    
    // Script Generator
    script_generator: 'Script Generator',
    script_generator_subtitle: 'AI-powered German faith-niche YouTube Shorts scripts',
    settings: 'Settings',
    ml_optimized_generation: 'ML-Optimized Generation',
    use_top_patterns: 'Use top performing patterns from analytics data',
    top_patterns: 'Top Performing Patterns',
    topic: 'Topic',
    topic_placeholder: 'e.g. God\'s love, Power of prayer, etc.',
    topic_required: 'Please enter a topic!',
    keywords: 'Keywords',
    keyword_placeholder: 'e.g. hope',
    add_keyword: 'Add Keyword',
    mode: 'Mode',
    use_analytics: 'Use Analytics (ML optimization)',
    analytics_disabled: 'Not enough analytics data for ML optimization',
    generate: 'Generate',
    ml_generate: 'ML-Optimized Generation',
    generating: 'Generating...',
    generated_script: 'Generated Script',
    script_success: 'Script generated successfully!',
    script_failed: 'Script generation failed',
    no_script_yet: 'No script generated yet.',
    enter_topic_generate: 'Enter a topic and click Generate!',
    hook: 'Hook',
    script: 'Script',
    full_script: 'Full Script',
    character_count: 'Character Count',
    hook_type: 'Hook Type',
    generated_with_analytics: 'ML-optimized',
    copy: 'Copy',
    copied: 'Copied to clipboard!',
    
    // Hook Library
    hook_library: 'Hook Library',
    hook_library_subtitle: 'Automatic and manual collection',
    hook_count: 'hook',
    search_hooks: 'Search hook text or tag...',
    all_modes: 'All Modes',
    all_types: 'All Types',
    sort_by: 'Sort',
    sort_date: 'Date',
    sort_retention: 'Retention %',
    sort_usage: 'Usage',
    create_hook: 'New Hook',
    create_hook_title: 'Create New Hook',
    hook_text: 'Hook Text',
    hook_text_placeholder: 'Weißt du, was wirklich zählt?',
    hook_type: 'Hook Type',
    avg_retention: 'Avg Retention %',
    retention: 'retention',
    usage_count: 'used',
    times_used: '× used',
    tags: 'Tags',
    tag_placeholder: 'e.g. hope',
    delete: 'Delete',
    add_tag: 'Add',
    no_hooks_yet: 'No hooks yet',
    no_results: 'No results',
    try_different_filters: 'Try different search filters',
    create_first_hook: 'Generate scripts or create hooks manually',
    hook_created: 'Hook created!',
    hook_deleted: 'Hook deleted',
    hook_text_required: 'Hook text is required!',
    hook_load_failed: 'Failed to load hook library',
    hook_create_failed: 'Failed to create hook',
    hook_delete_failed: 'Failed to delete',
    confirm_delete_hook: 'Are you sure you want to delete this hook?',
    loading: 'Loading...',
    
    // Hook Types
    emotional_trigger: 'Emotional Trigger',
    urgency: 'Urgency',
    identity_filter: 'Identity Filter',
    reverse_psychology: 'Reverse Psychology',
    not_for_everyone: 'Not For Everyone',
    dominance_line: 'Dominance Line',
    open_loop: 'Open Loop',
    
    // Video Factory
    video_factory: 'Video Factory',
    video_factory_subtitle: 'AI-powered video generation: TTS + B-roll + karaoke captions',
    select_script: 'Select Script',
    select_script_prompt: 'Choose a script...',
    voice_settings: 'Voice Settings (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'e.g. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stability',
    similarity_boost: 'Similarity Boost',
    style: 'Style',
    speaker_boost: 'Speaker Boost (recommended)',
    video_settings: 'Video Settings',
    broll_search: 'B-roll Search (Pexels)',
    broll_placeholder: 'e.g. faith, spirituality, peaceful (empty = auto topic)',
    broll_hint: 'If empty, uses script topic',
    background_music: 'Background Music URL (optional)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock music or custom URL (MP3)',
    start_generation: 'Start Video Generation',
    generation_in_progress: 'Generation in progress...',
    video_pipeline: 'Video Pipeline',
    generated_videos: 'Generated Videos',
    no_videos_yet: 'No generated videos yet',
    select_and_generate: 'Select a script and start video generation!',
    
    // Analytics
    analytics: 'Analytics Dashboard',
    analytics_subtitle: 'Performance metrics and insights',
    total_views: 'Total Views',
    total_likes: 'Total Likes',
    total_comments: 'Comments',
    new_subscribers: 'New Subscribers',
    avg_retention_rate: 'Avg Retention Rate',
    avg_swipe_rate: 'Avg Swipe Rate',
    excellent: 'Excellent',
    improvable: 'Improvable',
    hook_type_performance: 'Hook Type Performance',
    latest_metrics: 'Latest Metrics',
    no_analytics_yet: 'No analytics data yet',
    upload_csv_or_add_metrics: 'Upload Notion CSV or add metrics',
    
    // Notion Analytics
    notion_analytics: 'Notion Analytics',
    notion_subtitle: 'CSV import/export and ML optimization insights',
    import_csv: 'Import CSV',
    export_csv: 'Export Data',
    view_guide: 'Algorithm Guide',
    analytics_insights: 'Analytics Insights',
    imported_rows: 'Imported Rows',
    top_hooks: 'Top Performance Hooks',
    top_scripts: 'Top Performance Scripts',
    no_data_yet: 'No Notion data yet',
    import_csv_to_start: 'Import CSV to use ML optimization',
    
    // Settings
    settings_title: 'Settings',
    settings_subtitle: 'Profile and API key management',
    profile: 'Profile',
    api_keys: 'API Keys',
    api_keys_warning: '⚠️ Warning: Keys are stored in browser localStorage!',
    save_keys: 'Save Keys',
    keys_saved: 'API keys saved!',
    logout: 'Logout',
    logout_subtitle: 'End session',
    logout_success: 'Successfully logged out!',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    characters: 'characters',
    created_at: 'Created',
    updated_at: 'Updated'
  },
  
  pl: {
    // Navigation
    nav_overview: 'Przegląd',
    nav_scripts: 'Generator Skryptów',
    nav_hooks: 'Biblioteka Hooków',
    nav_videos: 'Fabryka Wideo',
    nav_analytics: 'Analityka',
    nav_notion: 'Analityka Notion',
    nav_settings: 'Ustawienia',
    nav_logout: 'Wyloguj',
    
    // Auth
    login_title: 'Zaloguj',
    register_title: 'Zarejestruj',
    email: 'E-mail',
    password: 'Hasło',
    name: 'Imię',
    login_button: 'Zaloguj',
    register_button: 'Zarejestruj',
    forgot_password: 'Zapomniałeś hasła',
    reset_password: 'Resetuj hasło',
    
    // Dashboard Overview
    welcome: 'Witaj',
    welcome_message: 'Gotowy do tworzenia profesjonalnych YouTube Shorts?',
    total_scripts: 'Wszystkie Skrypty',
    total_hooks: 'Wszystkie Hooki',
    avg_retention: 'Śr. Retention',
    swipe_rate: 'Wskaźnik Swipe %',
    recent_scripts: 'Ostatnie Skrypty',
    no_scripts_yet: 'Brak skryptów',
    create_first_script: 'Utwórz swój pierwszy skrypt w generatorze',
    quick_actions: 'Szybkie Akcje',
    script_generation: 'Generowanie Skryptów',
    script_generation_desc: 'Skrypty AI w niemieckiej niszy',
    video_creation: 'Tworzenie Wideo',
    video_creation_desc: 'TTS + B-roll + karaoke',
    analytics_upload: 'Przesyłanie Analityki',
    analytics_upload_desc: 'Import CSV z Notion',
    how_to_start: 'Jak zacząć?',
    how_to_start_desc: 'Postępuj zgodnie z krokami, aby stworzyć udane YouTube Shorts',
    step_1_title: 'Generuj skrypty AI',
    step_1_desc: 'Emocjonalne treści religijne',
    step_2_title: 'Prześlij dane analityczne',
    step_2_desc: 'Z CSV lub API Notion',
    step_3_title: 'Generacja zoptymalizowana ML',
    step_3_desc: 'Na podstawie najlepszych wzorców',
    step_4_title: 'Stwórz profesjonalne wideo',
    step_4_desc: 'Pełny pipeline wideo',
    
    // Script Generator
    script_generator: 'Generator Skryptów',
    script_generator_subtitle: 'Skrypty YouTube Shorts z AI (niemiecka nisza religijna)',
    settings: 'Ustawienia',
    ml_optimized_generation: 'Generacja Zoptymalizowana ML',
    use_top_patterns: 'Użyj najlepszych wzorców z danych analitycznych',
    top_patterns: 'Najlepsze Wzorce',
    topic: 'Temat',
    topic_placeholder: 'np. Miłość Boga, Moc modlitwy, itp.',
    topic_required: 'Proszę wprowadzić temat!',
    keywords: 'Słowa kluczowe',
    keyword_placeholder: 'np. nadzieja',
    add_keyword: 'Dodaj słowo kluczowe',
    mode: 'Tryb',
    use_analytics: 'Użyj analityki (optymalizacja ML)',
    analytics_disabled: 'Za mało danych analitycznych do optymalizacji ML',
    generate: 'Generuj',
    ml_generate: 'Generacja Zoptymalizowana ML',
    generating: 'Generowanie...',
    generated_script: 'Wygenerowany Skrypt',
    script_success: 'Skrypt wygenerowany pomyślnie!',
    script_failed: 'Generowanie skryptu nie powiodło się',
    no_script_yet: 'Jeszcze nie wygenerowano skryptu.',
    enter_topic_generate: 'Wprowadź temat i kliknij Generuj!',
    hook: 'Hook',
    script: 'Skrypt',
    full_script: 'Pełny Skrypt',
    character_count: 'Liczba znaków',
    hook_type: 'Typ Hooka',
    generated_with_analytics: 'Zoptymalizowany ML',
    copy: 'Kopiuj',
    copied: 'Skopiowano do schowka!',
    
    // Hook Library
    hook_library: 'Biblioteka Hooków',
    hook_library_subtitle: 'Kolekcja automatyczna i manualna',
    hook_count: 'hook',
    search_hooks: 'Szukaj tekstu hooka lub tagu...',
    all_modes: 'Wszystkie Tryby',
    all_types: 'Wszystkie Typy',
    sort_by: 'Sortuj',
    sort_date: 'Data',
    sort_retention: 'Retention %',
    sort_usage: 'Użycie',
    create_hook: 'Nowy Hook',
    create_hook_title: 'Utwórz Nowy Hook',
    hook_text: 'Tekst Hooka',
    hook_text_placeholder: 'Weißt du, was wirklich zählt?',
    hook_type: 'Typ Hooka',
    avg_retention: 'Śr. Retention %',
    retention: 'retention',
    usage_count: 'użyty',
    times_used: '× użyty',
    tags: 'Tagi',
    tag_placeholder: 'np. nadzieja',
    delete: 'Usuń',
    add_tag: 'Dodaj',
    no_hooks_yet: 'Brak hooków',
    no_results: 'Brak wyników',
    try_different_filters: 'Spróbuj innych kryteriów wyszukiwania',
    create_first_hook: 'Generuj skrypty lub twórz hooki ręcznie',
    hook_created: 'Hook utworzony!',
    hook_deleted: 'Hook usunięty',
    hook_text_required: 'Tekst hooka jest wymagany!',
    hook_load_failed: 'Nie udało się załadować biblioteki hooków',
    hook_create_failed: 'Nie udało się utworzyć hooka',
    hook_delete_failed: 'Nie udało się usunąć',
    confirm_delete_hook: 'Czy na pewno chcesz usunąć tego hooka?',
    loading: 'Ładowanie...',
    
    // Hook Types
    emotional_trigger: 'Wyzwalacz Emocjonalny',
    urgency: 'Pilność',
    identity_filter: 'Filtr Tożsamości',
    reverse_psychology: 'Odwrócona Psychologia',
    not_for_everyone: 'Nie Dla Każdego',
    dominance_line: 'Linia Dominacji',
    open_loop: 'Otwarta Pętla',
    
    // Video Factory
    video_factory: 'Fabryka Wideo',
    video_factory_subtitle: 'Generowanie wideo z AI: TTS + B-roll + napisy karaoke',
    select_script: 'Wybierz Skrypt',
    select_script_prompt: 'Wybierz skrypt...',
    voice_settings: 'Ustawienia Głosu (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'np. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stabilność',
    similarity_boost: 'Boost Podobieństwa',
    style: 'Styl',
    speaker_boost: 'Boost Głośnika (zalecane)',
    video_settings: 'Ustawienia Wideo',
    broll_search: 'Wyszukiwanie B-roll (Pexels)',
    broll_placeholder: 'np. wiara, duchowość, spokój (puste = auto temat)',
    broll_hint: 'Jeśli puste, użyje tematu skryptu',
    background_music: 'URL Muzyki Tła (opcjonalne)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Muzyka stockowa lub własny URL (MP3)',
    start_generation: 'Rozpocznij Generowanie Wideo',
    generation_in_progress: 'Generowanie w toku...',
    video_pipeline: 'Pipeline Wideo',
    generated_videos: 'Wygenerowane Wideo',
    no_videos_yet: 'Brak wygenerowanych wideo',
    select_and_generate: 'Wybierz skrypt i rozpocznij generowanie wideo!',
    
    // Analytics
    analytics: 'Panel Analityki',
    analytics_subtitle: 'Metryki wydajności i spostrzeżenia',
    total_views: 'Wszystkie Wyświetlenia',
    total_likes: 'Wszystkie Polubienia',
    total_comments: 'Komentarze',
    new_subscribers: 'Nowi Subskrybenci',
    avg_retention_rate: 'Śr. Wskaźnik Retention',
    avg_swipe_rate: 'Śr. Wskaźnik Swipe',
    excellent: 'Doskonały',
    improvable: 'Do poprawy',
    hook_type_performance: 'Wydajność Typu Hooka',
    latest_metrics: 'Najnowsze Metryki',
    no_analytics_yet: 'Brak danych analitycznych',
    upload_csv_or_add_metrics: 'Prześlij CSV z Notion lub dodaj metryki',
    
    // Notion Analytics
    notion_analytics: 'Analityka Notion',
    notion_subtitle: 'Import/export CSV i optymalizacja ML',
    import_csv: 'Importuj CSV',
    export_csv: 'Eksportuj Dane',
    view_guide: 'Przewodnik Algorytmu',
    analytics_insights: 'Spostrzeżenia Analityki',
    imported_rows: 'Zaimportowane Wiersze',
    top_hooks: 'Top Hooki Wydajności',
    top_scripts: 'Top Skrypty Wydajności',
    no_data_yet: 'Brak danych Notion',
    import_csv_to_start: 'Importuj CSV do optymalizacji ML',
    
    // Settings
    settings_title: 'Ustawienia',
    settings_subtitle: 'Zarządzanie profilem i kluczami API',
    profile: 'Profil',
    api_keys: 'Klucze API',
    api_keys_warning: '⚠️ Uwaga: Klucze są przechowywane w localStorage przeglądarki!',
    save_keys: 'Zapisz Klucze',
    keys_saved: 'Klucze API zapisane!',
    logout: 'Wyloguj',
    logout_subtitle: 'Zakończ sesję',
    logout_success: 'Pomyślnie wylogowano!',
    
    // Common
    save: 'Zapisz',
    cancel: 'Anuluj',
    close: 'Zamknij',
    edit: 'Edytuj',
    loading: 'Ładowanie...',
    error: 'Błąd',
    success: 'Sukces',
    characters: 'znaków',
    created_at: 'Utworzono',
    updated_at: 'Zaktualizowano'
  },
  
  nl: {
    // Navigation
    nav_overview: 'Overzicht',
    nav_scripts: 'Script Generator',
    nav_hooks: 'Hook Bibliotheek',
    nav_videos: 'Video Fabriek',
    nav_analytics: 'Analytics',
    nav_notion: 'Notion Analytics',
    nav_settings: 'Instellingen',
    nav_logout: 'Uitloggen',
    
    // Auth
    login_title: 'Inloggen',
    register_title: 'Registreren',
    email: 'E-mail',
    password: 'Wachtwoord',
    name: 'Naam',
    login_button: 'Inloggen',
    register_button: 'Registreren',
    forgot_password: 'Wachtwoord vergeten',
    reset_password: 'Wachtwoord resetten',
    
    // Dashboard Overview
    welcome: 'Welkom',
    welcome_message: 'Klaar om professionele YouTube Shorts te maken?',
    total_scripts: 'Totaal Scripts',
    total_hooks: 'Totaal Hooks',
    avg_retention: 'Gem. Retention',
    swipe_rate: 'Swipe Rate %',
    recent_scripts: 'Recente Scripts',
    no_scripts_yet: 'Nog geen scripts',
    create_first_script: 'Maak je eerste script in de generator',
    quick_actions: 'Snelle Acties',
    script_generation: 'Script Generatie',
    script_generation_desc: 'AI-aangedreven Duitse geloof scripts',
    video_creation: 'Video Creatie',
    video_creation_desc: 'TTS + B-roll + karaoke',
    analytics_upload: 'Analytics Upload',
    analytics_upload_desc: 'CSV import uit Notion',
    how_to_start: 'Hoe te beginnen?',
    how_to_start_desc: 'Volg deze stappen voor succesvolle YouTube Shorts',
    step_1_title: 'Genereer AI scripts',
    step_1_desc: 'Emotionele geloof-gebaseerde content',
    step_2_title: 'Upload analytics data',
    step_2_desc: 'Uit CSV of Notion API',
    step_3_title: 'ML-geoptimaliseerde generatie',
    step_3_desc: 'Gebaseerd op top patronen',
    step_4_title: 'Maak professionele video',
    step_4_desc: 'Volledige video pipeline',
    
    // Script Generator
    script_generator: 'Script Generator',
    script_generator_subtitle: 'AI-aangedreven Duitse geloof-niche YouTube Shorts scripts',
    settings: 'Instellingen',
    ml_optimized_generation: 'ML-Geoptimaliseerde Generatie',
    use_top_patterns: 'Gebruik top presterende patronen uit analytics gegevens',
    top_patterns: 'Top Patronen',
    topic: 'Onderwerp',
    topic_placeholder: 'bijv. Gods liefde, Kracht van gebed, enz.',
    topic_required: 'Voer een onderwerp in!',
    keywords: 'Trefwoorden',
    keyword_placeholder: 'bijv. hoop',
    add_keyword: 'Trefwoord toevoegen',
    mode: 'Modus',
    use_analytics: 'Analytics gebruiken (ML-optimalisatie)',
    analytics_disabled: 'Niet genoeg analytics data voor ML-optimalisatie',
    generate: 'Genereren',
    ml_generate: 'ML-Geoptimaliseerde Generatie',
    generating: 'Genereren...',
    generated_script: 'Gegenereerd Script',
    script_success: 'Script succesvol gegenereerd!',
    script_failed: 'Script generatie mislukt',
    no_script_yet: 'Nog geen script gegenereerd.',
    enter_topic_generate: 'Voer een onderwerp in en klik op Genereren!',
    hook: 'Hook',
    script: 'Script',
    full_script: 'Volledig Script',
    character_count: 'Aantal tekens',
    hook_type: 'Hook Type',
    generated_with_analytics: 'ML-geoptimaliseerd',
    copy: 'Kopiëren',
    copied: 'Gekopieerd naar klembord!',
    
    // Hook Library
    hook_library: 'Hook Bibliotheek',
    hook_library_subtitle: 'Automatische en handmatige collectie',
    hook_count: 'hook',
    search_hooks: 'Zoek hook tekst of tag...',
    all_modes: 'Alle Modi',
    all_types: 'Alle Types',
    sort_by: 'Sorteren',
    sort_date: 'Datum',
    sort_retention: 'Retention %',
    sort_usage: 'Gebruik',
    create_hook: 'Nieuwe Hook',
    create_hook_title: 'Nieuwe Hook Maken',
    hook_text: 'Hook Tekst',
    hook_text_placeholder: 'Weißt du, was wirklich zählt?',
    hook_type: 'Hook Type',
    avg_retention: 'Gem. Retention %',
    retention: 'retention',
    usage_count: 'gebruikt',
    times_used: '× gebruikt',
    tags: 'Tags',
    tag_placeholder: 'bijv. hoop',
    delete: 'Verwijderen',
    add_tag: 'Toevoegen',
    no_hooks_yet: 'Nog geen hooks',
    no_results: 'Geen resultaten',
    try_different_filters: 'Probeer andere zoekcriteria',
    create_first_hook: 'Genereer scripts of maak handmatig hooks',
    hook_created: 'Hook aangemaakt!',
    hook_deleted: 'Hook verwijderd',
    hook_text_required: 'Hook tekst is vereist!',
    hook_load_failed: 'Laden van hook bibliotheek mislukt',
    hook_create_failed: 'Aanmaken van hook mislukt',
    hook_delete_failed: 'Verwijderen mislukt',
    confirm_delete_hook: 'Weet je zeker dat je deze hook wilt verwijderen?',
    loading: 'Laden...',
    
    // Hook Types
    emotional_trigger: 'Emotionele Trigger',
    urgency: 'Urgentie',
    identity_filter: 'Identiteitsfilter',
    reverse_psychology: 'Omgekeerde Psychologie',
    not_for_everyone: 'Niet Voor Iedereen',
    dominance_line: 'Dominantielijn',
    open_loop: 'Open Loop',
    
    // Video Factory
    video_factory: 'Video Fabriek',
    video_factory_subtitle: 'AI-aangedreven videogeneratie: TTS + B-roll + karaoke ondertiteling',
    select_script: 'Selecteer Script',
    select_script_prompt: 'Kies een script...',
    voice_settings: 'Stem Instellingen (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'bijv. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stabiliteit',
    similarity_boost: 'Gelijkenis Boost',
    style: 'Stijl',
    speaker_boost: 'Speaker Boost (aanbevolen)',
    video_settings: 'Video Instellingen',
    broll_search: 'B-roll Zoeken (Pexels)',
    broll_placeholder: 'bijv. geloof, spiritualiteit, rustig (leeg = auto onderwerp)',
    broll_hint: 'Als leeg, gebruikt script onderwerp',
    background_music: 'Achtergrondmuziek URL (optioneel)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock muziek of eigen URL (MP3)',
    start_generation: 'Start Video Generatie',
    generation_in_progress: 'Generatie bezig...',
    video_pipeline: 'Video Pipeline',
    generated_videos: 'Gegenereerde Videos',
    no_videos_yet: 'Nog geen gegenereerde videos',
    select_and_generate: 'Selecteer een script en start videogeneratie!',
    
    // Analytics
    analytics: 'Analytics Dashboard',
    analytics_subtitle: 'Prestatiemetrieken en inzichten',
    total_views: 'Totaal Weergaven',
    total_likes: 'Totaal Likes',
    total_comments: 'Reacties',
    new_subscribers: 'Nieuwe Abonnees',
    avg_retention_rate: 'Gem. Retention Rate',
    avg_swipe_rate: 'Gem. Swipe Rate',
    excellent: 'Uitstekend',
    improvable: 'Verbeterbaar',
    hook_type_performance: 'Hook Type Prestatie',
    latest_metrics: 'Laatste Metrieken',
    no_analytics_yet: 'Nog geen analytics data',
    upload_csv_or_add_metrics: 'Upload Notion CSV of voeg metrieken toe',
    
    // Notion Analytics
    notion_analytics: 'Notion Analytics',
    notion_subtitle: 'CSV import/export en ML-optimalisatie inzichten',
    import_csv: 'CSV Importeren',
    export_csv: 'Data Exporteren',
    view_guide: 'Algoritme Gids',
    analytics_insights: 'Analytics Inzichten',
    imported_rows: 'Geïmporteerde Rijen',
    top_hooks: 'Top Prestatie Hooks',
    top_scripts: 'Top Prestatie Scripts',
    no_data_yet: 'Nog geen Notion data',
    import_csv_to_start: 'Importeer CSV voor ML-optimalisatie',
    
    // Settings
    settings_title: 'Instellingen',
    settings_subtitle: 'Profiel en API sleutelbeheer',
    profile: 'Profiel',
    api_keys: 'API Sleutels',
    api_keys_warning: '⚠️ Waarschuwing: Sleutels worden opgeslagen in browser localStorage!',
    save_keys: 'Sleutels Opslaan',
    keys_saved: 'API sleutels opgeslagen!',
    logout: 'Uitloggen',
    logout_subtitle: 'Sessie beëindigen',
    logout_success: 'Succesvol uitgelogd!',
    
    // Common
    save: 'Opslaan',
    cancel: 'Annuleren',
    close: 'Sluiten',
    edit: 'Bewerken',
    loading: 'Laden...',
    error: 'Fout',
    success: 'Succes',
    characters: 'tekens',
    created_at: 'Aangemaakt',
    updated_at: 'Bijgewerkt'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem('language') || 'hu'
  );

  useEffect(() => {
    localStorage.setItem('language', language);
    // Sync i18n language when LanguageContext language changes
    const langCode = language === 'us' ? 'en' : language;
    i18n.changeLanguage(langCode);
  }, [language]);

  // Create t function that depends on current language
  // Using useCallback to ensure stable reference but updated closure
  const t = React.useCallback((key) => {
    // Map 'us' to 'en' for backwards compatibility
    const langCode = language === 'us' ? 'en' : language;
    return translations[langCode]?.[key] || translations['hu'][key] || key;
  }, [language]);

  // Memoize context value to prevent unnecessary re-renders
  const contextValue = React.useMemo(() => ({
    language,
    setLanguage,
    t
  }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
